export const ModalActionTypes = {
  TOGGLE_MODAL: 'TOGGLE_MODAL',
  CHANGE_MODAL_TYPE: 'CHANGE_MODAL_TYPE',

  LABEL_CHANGE: 'LABEL_CHANGE',
  PHOTO_URL_CHANGE: 'PHOTO_URL_CHANGE',
  PASSWORD_CHANGE: 'PASSWORD_CHANGE',
};
